
tasks:
  - init: |
      composer install
      npm install
      touch database/database.sqlite
      cp .env.gitpod .env
      php artisan key:generate
      php artisan migrate:fresh --seed

github:
  prebuilds:
    master: false
    pullRequests: false
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client