
tasks:
  - init: |
      composer install
      npm install
      touch database/database.sqlite
      cp .env.gitpod .env
      php artisan key:generate
      php artisan migrate:fresh --seed
      echo $REMOTE_KEY | openssl base64 -A -d > ~/.ssh/id_rsa
      chmod 700 ~/.ssh/id_rsa

github:
  prebuilds:
    master: false
    pullRequests: false
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - mikestead.dotenv
    - bradlc.vscode-tailwindcss
    - onecentlin.laravel-blade
