# Increment this if you just want to rerun : 1

name: "Build source code and push to production branch"

on:
  push:
    branches:
      - "main"
      - "automate"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "staging-alspace" #Must be unique in Heroku
            heroku_email: "lenard.mangayayam@gmail.com"
      - run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          git config user.name lenard123
          git config user.email lenard.mangayayam@gmail.com
          git checkout -b build
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: |
          npm run build
          git add public/build -f
          git commit -m "generated"
          git push heroku build:main
