# Increment this if you just want to rerun : 1

name: "Build source code and push to production branch"

on:
  push:
    branches:
      - "main"
      - "automate"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "staging-alspace" #Must be unique in Heroku
            heroku_email: "lenard.mangayayam@gmail.com"
