
name: "Trigger Deploy Command on Azure VM"

on:
  push:
    branches:
      - "build"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy Via SSH"
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/alspace
            composer deploy
          host: ${{ secrets.VM_HOST }}
          user: ${{ secrets.VM_USER }}
          key:  ${{ secrets.VM_KEY }}
          pass: ${{ secrets.VM_PASS }}
