# Increment this if you just want to rerun : 1

name: "Deploy to production server"

on:
  push:
    branches:
      - "main"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "alspace" #Must be unique in Heroku
            heroku_email: "lenard.mangayayam@gmail.com"
